name: Deploy to Render

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Verify build
        run: npm run build
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      
      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          clear_cache: true
