name: Deploy to Render

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Verify build
        run: npm run build
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      
      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/deploy/srv-cvibig1r0fns738c9pmg?key=JhmN8JTiW8s"
